version: "3.8"
services:
  mysql:
    container_name: mysql
    build: ./db
    volumes:
      - type: volume
        source: trio-volume
        target: /var/lib/mysql
    networks:
      - trio-net
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: flask-db
  flask-app:
    container_name: flask-app
    build: ./flask-app
    networks:
      - trio-net
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - "mysql"
  nginx:
    container_name: nginx
    image: nginx:latest
    networks:
      - trio-net
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - target: 80
        published: 80
        protocol: tcp
volumes:
  trio-volume:
networks:
  trio-net: